"""initial_schema

Revision ID: 58e5f1bc23af
Revises:
Create Date: 2026-06-13 16:05:14.565790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58e5f1bc23af"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospital",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("subdomain", sa.String(length=50), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subdomain"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("contact", sa.String(length=20), nullable=True),
        sa.Column("password", sa.String(length=200), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("blood_type", sa.String(length=10), nullable=True),
        sa.Column("height", sa.String(length=20), nullable=True),
        sa.Column("weight_baseline", sa.String(length=20), nullable=True),
        sa.Column("allergies", sa.Text(), nullable=True),
        sa.Column("specialization", sa.String(length=100), nullable=True),
        sa.Column("qualification", sa.String(length=200), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("consultation_fee", sa.Float(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hospital_id", "contact", name="uq_user_hospital_contact"),
        sa.UniqueConstraint("hospital_id", "email", name="uq_user_hospital_email"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("ix_user_hospital_active", ["hospital_id", "is_active"], unique=False)
        batch_op.create_index("ix_user_hospital_role", ["hospital_id", "role"], unique=False)

    op.create_table(
        "appointment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("date_str", sa.String(length=20), nullable=False),
        sa.Column("time_str", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("symptoms", sa.Text(), nullable=True),
        sa.Column("pain_level", sa.Integer(), nullable=True),
        sa.Column("followup_days", sa.Integer(), nullable=True),
        sa.Column("clinical_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.create_index("ix_appointment_date", ["hospital_id", "date_str"], unique=False)
        batch_op.create_index("ix_appointment_doctor", ["hospital_id", "doctor_id"], unique=False)
        batch_op.create_index(
            "ix_appointment_doctor_slot", ["hospital_id", "doctor_id", "date_str", "time_str"], unique=False
        )
        batch_op.create_index("ix_appointment_hospital_status", ["hospital_id", "status"], unique=False)
        batch_op.create_index("ix_appointment_patient", ["hospital_id", "patient_id"], unique=False)

    op.create_table(
        "invoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("consultation_fee", sa.Float(), nullable=True),
        sa.Column("lab_charges", sa.Float(), nullable=True),
        sa.Column("pharmacy_charges", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hospital_id", "appointment_id", name="uq_invoice_appointment"),
    )
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.create_index("ix_invoice_patient", ["hospital_id", "patient_id"], unique=False)
        batch_op.create_index("ix_invoice_status", ["hospital_id", "status"], unique=False)

    op.create_table(
        "lab_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("test_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("result_text", sa.Text(), nullable=True),
        sa.Column("ordered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_test", schema=None) as batch_op:
        batch_op.create_index("ix_lab_test_appointment", ["hospital_id", "appointment_id"], unique=False)
        batch_op.create_index("ix_lab_test_hospital_status", ["hospital_id", "status"], unique=False)
        batch_op.create_index("ix_lab_test_patient", ["hospital_id", "patient_id"], unique=False)

    op.create_table(
        "prescription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("medication", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescription", schema=None) as batch_op:
        batch_op.create_index("ix_prescription_doctor", ["hospital_id", "doctor_id"], unique=False)
        batch_op.create_index("ix_prescription_hospital_status", ["hospital_id", "status"], unique=False)
        batch_op.create_index("ix_prescription_patient", ["hospital_id", "patient_id"], unique=False)

    op.create_table(
        "rating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hospital_id", "appointment_id", name="uq_rating_appointment"),
    )
    with op.batch_alter_table("rating", schema=None) as batch_op:
        batch_op.create_index("ix_rating_doctor", ["hospital_id", "doctor_id"], unique=False)
        batch_op.create_index("ix_rating_patient", ["hospital_id", "patient_id"], unique=False)

    op.create_table(
        "vitals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.String(length=20), nullable=True),
        sa.Column("heart_rate", sa.String(length=20), nullable=True),
        sa.Column("blood_pressure", sa.String(length=20), nullable=True),
        sa.Column("temperature", sa.String(length=20), nullable=True),
        sa.Column("taken_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospital.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hospital_id", "appointment_id", name="uq_vitals_appointment"),
    )
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.create_index("ix_vitals_patient", ["hospital_id", "patient_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.drop_index("ix_vitals_patient")

    op.drop_table("vitals")
    with op.batch_alter_table("rating", schema=None) as batch_op:
        batch_op.drop_index("ix_rating_patient")
        batch_op.drop_index("ix_rating_doctor")

    op.drop_table("rating")
    with op.batch_alter_table("prescription", schema=None) as batch_op:
        batch_op.drop_index("ix_prescription_patient")
        batch_op.drop_index("ix_prescription_hospital_status")
        batch_op.drop_index("ix_prescription_doctor")

    op.drop_table("prescription")
    with op.batch_alter_table("lab_test", schema=None) as batch_op:
        batch_op.drop_index("ix_lab_test_patient")
        batch_op.drop_index("ix_lab_test_hospital_status")
        batch_op.drop_index("ix_lab_test_appointment")

    op.drop_table("lab_test")
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.drop_index("ix_invoice_status")
        batch_op.drop_index("ix_invoice_patient")

    op.drop_table("invoice")
    with op.batch_alter_table("appointment", schema=None) as batch_op:
        batch_op.drop_index("ix_appointment_patient")
        batch_op.drop_index("ix_appointment_hospital_status")
        batch_op.drop_index("ix_appointment_doctor_slot")
        batch_op.drop_index("ix_appointment_doctor")
        batch_op.drop_index("ix_appointment_date")

    op.drop_table("appointment")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_hospital_role")
        batch_op.drop_index("ix_user_hospital_active")

    op.drop_table("user")
    op.drop_table("hospital")
    # ### end Alembic commands ###
