"""add tenant indexes and constraints

Revision ID: 9eb8f3530f9f
Revises: 
Create Date: 2026-05-20 11:53:19.332725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb8f3530f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_date', ['hospital_id', 'date_str'], unique=False)
        batch_op.create_index('ix_appointment_doctor', ['hospital_id', 'doctor_id'], unique=False)
        batch_op.create_index('ix_appointment_doctor_slot', ['hospital_id', 'doctor_id', 'date_str', 'time_str'], unique=False)
        batch_op.create_index('ix_appointment_hospital_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_appointment_patient', ['hospital_id', 'patient_id'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_patient', ['hospital_id', 'patient_id'], unique=False)
        batch_op.create_index('ix_invoice_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_unique_constraint('uq_invoice_appointment', ['hospital_id', 'appointment_id'])

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.create_index('ix_lab_test_appointment', ['hospital_id', 'appointment_id'], unique=False)
        batch_op.create_index('ix_lab_test_hospital_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_lab_test_patient', ['hospital_id', 'patient_id'], unique=False)

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.create_index('ix_prescription_doctor', ['hospital_id', 'doctor_id'], unique=False)
        batch_op.create_index('ix_prescription_hospital_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_prescription_patient', ['hospital_id', 'patient_id'], unique=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index('ix_rating_doctor', ['hospital_id', 'doctor_id'], unique=False)
        batch_op.create_index('ix_rating_patient', ['hospital_id', 'patient_id'], unique=False)
        batch_op.create_unique_constraint('uq_rating_appointment', ['hospital_id', 'appointment_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_hospital_active', ['hospital_id', 'is_active'], unique=False)
        batch_op.create_index('ix_user_hospital_role', ['hospital_id', 'role'], unique=False)
        batch_op.create_unique_constraint('uq_user_hospital_contact', ['hospital_id', 'contact'])
        batch_op.create_unique_constraint('uq_user_hospital_email', ['hospital_id', 'email'])

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.create_index('ix_vitals_patient', ['hospital_id', 'patient_id'], unique=False)
        batch_op.create_unique_constraint('uq_vitals_appointment', ['hospital_id', 'appointment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vitals_appointment', type_='unique')
        batch_op.drop_index('ix_vitals_patient')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_hospital_email', type_='unique')
        batch_op.drop_constraint('uq_user_hospital_contact', type_='unique')
        batch_op.drop_index('ix_user_hospital_role')
        batch_op.drop_index('ix_user_hospital_active')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rating_appointment', type_='unique')
        batch_op.drop_index('ix_rating_patient')
        batch_op.drop_index('ix_rating_doctor')

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_index('ix_prescription_patient')
        batch_op.drop_index('ix_prescription_hospital_status')
        batch_op.drop_index('ix_prescription_doctor')

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.drop_index('ix_lab_test_patient')
        batch_op.drop_index('ix_lab_test_hospital_status')
        batch_op.drop_index('ix_lab_test_appointment')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_appointment', type_='unique')
        batch_op.drop_index('ix_invoice_status')
        batch_op.drop_index('ix_invoice_patient')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_patient')
        batch_op.drop_index('ix_appointment_hospital_status')
        batch_op.drop_index('ix_appointment_doctor_slot')
        batch_op.drop_index('ix_appointment_doctor')
        batch_op.drop_index('ix_appointment_date')

    # ### end Alembic commands ###
